#!/usr/bin/env python3
"""Generate data.js from PDT method .md files."""

import os, re, json

ROOT = os.path.dirname(os.path.abspath(__file__))
GITBOOK_BASE = "https://productdesigntoolkit.gitbook.io/methods"

SPACES = {
    "strategy-space": {"name": "Strategy Space", "label": "WHY",  "color": "#00E5CC"},
    "problem-space":  {"name": "Problem Space",  "label": "WHAT", "color": "#FFD600"},
    "solution-space": {"name": "Solution Space", "label": "WHAT", "color": "#FFAB00"},
    "product-space":  {"name": "Product Space",  "label": "HOW",  "color": "#2979FF"},
    "market-space":   {"name": "Market Space",   "label": "WHEN", "color": "#F50057"},
}


def get_frontmatter(content):
    if not content.startswith("---"):
        return {}, content
    end = content.find("\n---", 3)
    if end == -1:
        return {}, content
    fm_raw = content[4:end]
    rest = content[end + 4:].lstrip("\n")
    fm = {}
    for line in fm_raw.splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            fm[k.strip()] = v.strip().strip('"')
    return fm, rest


def get_section(content, heading):
    """Extract content of a markdown section (## or ### heading, with or without colon)."""
    pattern = rf"(?m)^#{'{2,3}'}\s+{re.escape(heading)}:?\s*\n+([\s\S]+?)(?=\n#{'{2,}'}\s|\Z)"
    m = re.search(pattern, content, re.IGNORECASE)
    if not m:
        return ""
    text = m.group(1).strip()
    # Remove markdown bold/italic, links
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"\[(.+?)\]\(.+?\)", r"\1", text)
    text = re.sub(r"[*_]", "", text)
    # First paragraph only
    para = text.split("\n\n")[0].strip()
    # Remove list markers for single-line descriptions
    para = re.sub(r"^\d+\.\s+|^[-*]\s+", "", para, flags=re.MULTILINE)
    return para[:400]


def get_title(content):
    m = re.search(r"^#\s+(.+)$", content, re.MULTILINE)
    return m.group(1).strip() if m else None


def gitbook_url(space_key, filename):
    slug = filename.replace(".md", "").lower()
    slug = re.sub(r"[_\s]+", "-", slug)
    slug = re.sub(r"-+", "-", slug).strip("-")
    return f"{GITBOOK_BASE}/{space_key}/{slug}"


def build():
    methods = {}
    for space_key in SPACES:
        space_dir = os.path.join(ROOT, space_key)
        if not os.path.isdir(space_dir):
            continue
        methods[space_key] = []
        for filename in sorted(os.listdir(space_dir)):
            if not filename.endswith(".md") or filename == "README.md":
                continue
            filepath = os.path.join(space_dir, filename)
            with open(filepath, encoding="utf-8") as f:
                raw = f.read()
            fm, content = get_frontmatter(raw)
            title = fm.get("title") or get_title(content)
            if not title:
                print(f"  skip (no title): {filename}")
                continue
            desc = fm.get("description") or get_section(content, "Kurzbeschreibung")
            use  = get_section(content, "Einsatzzweck")
            methods[space_key].append({
                "title":    title,
                "space":    space_key,
                "file":     filename,
                "desc":     desc,
                "use":      use,
                "gitbook":  gitbook_url(space_key, filename),
            })
        print(f"{SPACES[space_key]['name']}: {len(methods[space_key])} methods")

    out = f"// Auto-generated by build.py – do not edit manually\nconst PDT_DATA = {json.dumps({'spaces': SPACES, 'methods': methods}, ensure_ascii=False, indent=2)};\n"
    with open(os.path.join(ROOT, "data.js"), "w", encoding="utf-8") as f:
        f.write(out)
    total = sum(len(v) for v in methods.values())
    print(f"\n✓ data.js written — {total} methods total")


if __name__ == "__main__":
    build()
